// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZAxqqeHO_UPB0Z8wFbxD6XyD_cbguQds',
    appId: '1:760760627618:web:538ac57947f58c3e6482fb',
    messagingSenderId: '760760627618',
    projectId: 'mobile-cource-lab-7',
    authDomain: 'mobile-cource-lab-7.firebaseapp.com',
    storageBucket: 'mobile-cource-lab-7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdJzHoy9G14u1yX6W7fVFXkuI0WbjH_5k',
    appId: '1:760760627618:android:5e56da299c1cf4d86482fb',
    messagingSenderId: '760760627618',
    projectId: 'mobile-cource-lab-7',
    storageBucket: 'mobile-cource-lab-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKI8IDg7kNfOKF4MC6Y5kH-5dPz21o8Tk',
    appId: '1:760760627618:ios:3c40407834d5c8c26482fb',
    messagingSenderId: '760760627618',
    projectId: 'mobile-cource-lab-7',
    storageBucket: 'mobile-cource-lab-7.appspot.com',
    iosClientId: '760760627618-0n6drabsjj5g6d326utafao016gphp1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKI8IDg7kNfOKF4MC6Y5kH-5dPz21o8Tk',
    appId: '1:760760627618:ios:3c40407834d5c8c26482fb',
    messagingSenderId: '760760627618',
    projectId: 'mobile-cource-lab-7',
    storageBucket: 'mobile-cource-lab-7.appspot.com',
    iosClientId: '760760627618-0n6drabsjj5g6d326utafao016gphp1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab7',
  );
}
